### PR TITLE
Kill VOOT support

### PR DESCRIPTION
**Pull request by xavierba**
This PR removes support for VOOT in Sympa.
It is not clear if there are any users of this feature. The code is bit-roting and VOOT itself seems dormant at best. 
As mentioned on IRC, this is completely untested, not even build tested.

### CODE REVIEW

**Comment by dverdin** [comment]
Actually, I don't know if it is still used. But if it is, it will be by the GÉANT community.
We should maybe ask them about it before removing it, even though it is unlikely they still use it.
I had a hard time making them use Sympa, I'd better not get into trouble with them.
Any problem about postponing this removal until we have their opinion?

**Comment by dverdin** [comment]
On this topic, I wold add that having working code for Oauth is probably useful for the future of Sympa. I would rather have keep it than just drop it. the premise "I don't know if somebody uses it" seems thin to me. has the question been asked to the mailing lists?

**Comment by xavierba** [comment]
@dverdin, no problem for postponing. Do you have a way to reach out to Géant community ?
I have not asked on the mailing list and this is indeed a better idea than a raw PR. Anyway, it's very unlikely the code is used, as it's not even distributed in the tarball.

**Comment by dverdin** [comment]
Just to let you know: I had a contact with the head of PMO at GÉANT. He told me he would check about it.
Let me be clear: as for my own needs, I don't care about VOOT for now. But GÉANT is a very strong support for Sympa in Europe and I don't want to get in trouble with them. After all, they paid @markov to develop VOOT in the first place. They could certainly contribute further.

**Comment by ikedas** [comment]
I prepared additional removal of codes. @xavierba, you may cherry-pick it (or I can separately merge both changes by you and me).
https://github.com/xavierba/sympa/compare/kill_voot...ikedas:xavierba/kill_voot

**Comment by racke** [comment]
> Just to let you know: I had a contact with the head of PMO at GÉANT. He told me he would check about it.
> Let me be clear: as for my own needs, I don't care about VOOT for now. But GÉANT is a very strong support for Sympa in Europe and I don't want to get in trouble with them. After all, they paid @markov to develop VOOT in the first place. They could certainly contribute further.

I'm not aware that GÉANT is a very strong support for Sympa ... At any rate, the implementation was done 6 years ago and it isn't really functional until you utilize the ext directory.

Even if they still use it, the removal can be reversed but needs a integration of the complete VOOT code.

**Comment by ikedas** [comment]
FYI:
  * [Description about VOOT](https://wiki.geant.org/display/gn3pjra3/VOOT+-+Cross+Domain+Groupinformation+Exchange) by JRA3

Development of VOOT looks quieting down after publication of [SCIM](https://tools.ietf.org/html/rfc7642) as RFC 7642 - 7644.  It is not so *un*usual that development of protocol is gave up, even much it has been paid. And its value may not be masured by its deliverables).

Anyways I'll merge this PR to remove works for VOOT from Sympa.

**Comment by racke** [comment]
Thanks for the pointer, @ikedas. Please merge the PR :+1:

**Pull request merged**
