### PR TITLE
Refactor sympa.pl

### PR DESCRIPTION
**Pull request by ikedas**
* Split functions of sympa.pl into submodules.
  * Rename and merge some of sympa.pl commands: "`sympa.pl --add=list@dom ...`" to "`sympa.pl add ... list@dom`" and so on.
  * `sympa.pl` was renamed to `sympa`, and with a symlink, older name is still usable.

See POD in `sympa.pl.in` and `Sympa/CLI/*.pm` about changes.

### CODE REVIEW

**Comment by racke** [comment]
Great idea! Makes it a lot easier to add new commands as well. :+1:

**Comment by ikedas** [comment]
@racke, I have anothor idea that `sympa.pl` would be renamed to `sympa` (It might be better to leave the link to `sympa.pl` for backward compatibility).

**Comment by racke** [comment]
Yes, please do so! I already doing that in the Debian package and in my Ansible role.

**Comment by ikedas** [comment]
Changes on command line (note that older form may still be usable).

| Old format | New format |
| -- | -- |
| `sympa.pl` `--add=`_list_@_domain_ \[ `--role`=_role_ \] \[ `--quiet` \] \[ `--notify` \] \[ `--force` \] | `sympa` `add` \[ `--role`=_role_ \] \[ `--quiet` \] \[ `--notify` \] \[ `--force` \] _list_`@`_domain_ |
| `sympa.pl` `--add_list=`_family\_name_ `--robot=`_robot\_name_ `--input_file=`_/path/to/file.xml_ | `sympa` `create` `--input_file=`_/path/to/file.xml_ _family\_name_`@@`_robot\_name_ |
| `sympa.pl` `--change_user_email` `--current_email=`_current_ `--new_email=`_new_ | `sympa` `user move` _current_ _new_ |
| `sympa.pl` `--close_family=`_family\_name_ `--robot=`_robot\_name_ | `sympa` `close` _family\_name_`@@`_robot\_name_ |
| `sympa.pl` `--close_list=`_list_\[`@`_robot_\] | `sympa` `close` _list_\[`@`_robot_\] |
| `sympa.pl` `--conf_2_db` | TBC. |
| `sympa.pl` `--copy_list=`_listname_`@`_robot_ `--new_listname=`_newlistname_ `--new_listrobot=`_newrobot_ | `sympa` `move --copy` _listname_`@`_robot_ _newlistname_`@`_newrobot_ |
| `sympa.pl` `--create_list` `--robot=`_robot\_name_ `--input_file=`_/path/to/file.xml_ | `sympa` `create` `--input_file=`_/path/to/file.xml_ _robot\_name_ |
| `sympa.pl` `--del=`_list_`@`_domain_ \[ `--role`=_role_ \] \[ `--quiet` \] \[ `--notify` \] \[ `--force` \] | `sympa` `del` \[ `--role`=_role_ \] \[ `--quiet` \] \[ `--notify` \] \[ `--force` \] _list_`@`_domain_ |
| `sympa.pl` `--dump_users` `--list=`_list_@_domain_ \[ `--role=`_roles_ \] | `sympa` `dump` \[ `--roles=`_roles_ \] _list_`@`_domain_ |
| `sympa.pl` `--dump_users` `--list=ALL` \[ `--role=`_roles_ \] | `sympa` `dump` \[ `--roles=`_roles_ \] `"*"` |
| `sympa.pl` `--health_check` | `sympa` `check` |
| `sympa.pl` `--instantiate_family=`_family\_name_ `--robot=`_robot\_name_ `--input_file=`_/path/to/file.xml_ \[ `--close_unknown` \] \[ `--quiet` \] | `sympa` `instantiate` `--input_file=`_/path/to/file.xml_ \[ `--close_unknown` \] \[ `--quiet` \] _family\_name_`@@`_robot\_name_ |
| `sympa.pl` `--lowercase` | TBC. |
| `sympa.pl` `--make_alias_file` \[ `--robot` robot \] | TBC. |
| `sympa.pl` `--modify_list=`_family\_name_ `--robot=`_robot\_name_ `--input_file=`_/path/to/file.xml_ | `sympa` `update` `--input_file=`_/path/to/file.xml_ _family\_name_`@@`_robot\_name_ |
| `sympa.pl` `--open_list=`_list_\[`@`_robot_\] \[ `--notify` \] | `sympa` `open` \[ `--notify` \] _list_\[`@`_robot_\] |
| `sympa.pl` `--purge_list`=_list_\[`@`_robot_\] | `sympa` `close` `--purge` _list_\[`@`_robot_\] |
| `sympa.pl` `--show_pending_lists`=_robot_ | TBC. |
| `sympa.pl` `--rebuildarc`=_list_\[_@robot_\] | TBC. |
| `sympa.pl` `--reload_list_config` \[ `--list=`_mylist_@_mydom_ \] \[ `--robot=`_mydom_ \] | TBC. |
| `sympa.pl` `--rename_list=`_listname_`@`_robot_ `--new_listname=`_newlistname_ `--new_listrobot=`_newrobot_ | `sympa` `move` _listname_`@`_robot_ _newlistname_`@`_newrobot_ |
| `sympa.pl` `--send_digest` \[ `--keep_digest` \] | TBC. |
| `sympa.pl` `--restore_users` `--list=`_list_@_domain_&#124;`ALL` \[ `--role=`_roles_ \] | `sympa` `restore` \[ `--roles=`_roles_ \] _list_`@`_domain_ | `sympa` `restore` \[ `--roles=`_roles_ \] `"*"` |
| `sympa.pl` `--sync_include=`_listname_`@`_robot_ \[ `--role=`_role_ \] | `sympa` `include` \[ `--role=`_role_ \] _listname_`@`_robot_ |
| `sympa.pl` `--sync_list_db` \[ `--list=`_listname_@_robot_ \] | TBC. |
| `sympa.pl` `--upgrade` \[ `--from=`_X_ \] \[ `--to=`_Y_ \] | `sympa` `upgrade` \[ @--from=`_X_ \] \[ `--to=`_Y_ \] |
| `sympa.pl` `--upgrade_shared` \[ `--list=`_X_ \] \[ `--robot=`_Y_ \] | TBC. |
| `sympa.pl` `--md5_digest=`_password_ | TBC. |
| `sympa.pl` `-v`, `sympa.pl` `--version` | `sympa` `version` |

**Comment by racke** [comment]
Looks nice :+1: 

sympa move --copy listname@robot newlistname@newrobot

This should be really `sympa copy`, otherwise it is quite confusing and too much to type.

**Comment by racke** [comment]
Maybe you can post that new schema on the mailing list for more feedback?

**Comment by ikedas** [comment]
> sympa move --copy listname@robot newlistname@newrobot
> 
> This should be really `sympa copy`, otherwise it is quite confusing and too much to type.

`sympa move --copy` and `sympa move` use the same Sympa::Request handler.  It sounds true that this is not intuitive for the user.

I think of two:
- Add `sympa copy` as an alias of `sympa move --copy`.
- All changes will be subject to prompt confirmation, and that behavior can be overridden with any option, such as `-y`, `--assume-yes`.

---
Eventually, I'd like to integrate the other command line tools into `sympa`, including `sympa_wizard` and miscellaneous utilities under `src/bin`.

**Comment by racke** [comment]
Alias is an idea to solve the "move --copy" predicament. You could also add CLI::copy which inherits CLI::Move. Integration the other CLI tools is also a really good idea :+1:

**Comment by racke** [comment]
I'm not a friend of a prompt confirmation. If you want to do that, please add a configuration option to waive that confirmation without requiring -y.

**Pull request merged**
