### PR TITLE
Limited personalization

### LINKED ISSUE #1037: Personalization (merge_feature) should be limited
Version
-------

6.2.58 and earlier

Expected behavior
-----------------

  - If personalization is enabled, the messages posted only by limited users should be allowed personalization.
  - Or, scope of personalization should be limited to where owners can control: Only footer/header.

Actual behavior
---------------

  - Once personalization is enabled, any users who were allowed posting can use this feature.
  - And, entire text body of the message can be in the scope of conversion.

### PR DESCRIPTION
**Pull request by ikedas**
Limit personalization:

- Only when posted from WWSympa, entire text will be converted. Otherwise only footer/header will be converted.

This may fix #1037 .

### CODE REVIEW

**Comment by racke** [comment]
I agree with you that personalization should be restricted. However, I have existing projects where personalized emails are sent by email to Sympa. I suggest to control this by scenari.

**Comment by ikedas** [comment]
racke, thanks for comment.

Using scenario seems worth considering.
Another idea I came up with at first is subdividing the value of `merge_feature` parameter, e.g. `full`, `footer` and `none` instead of `on` & `off`.

**Comment by racke** [comment]
More detailed configuration makes a lot of sense to me. I suggest that we add an additional configuration parameter which comes with `merge_feature` instead of subdividing it.

For example `merge_parts` with values like full, footer, body.

As everything else is controlled by scenari, it would make sense to add one for the merge_feature too.

**Comment by ikedas** [comment]
> More detailed configuration makes a lot of sense to me. I suggest that we add an additional configuration parameter which comes with `merge_feature` instead of subdividing it.
> 
> For example `merge_parts` with values like full, footer, body.
> 
> As everything else is controlled by scenari, it would make sense to add one for the merge_feature too.

Ok, I'll think of adding new parameter and scenario.

**Comment by ikedas** [comment]
@racke, I added new parameters they may take a value either of `none`, `footer` (only header and footer) or `all` (header, footer and body).
  - `personalization.web_apply_on`: By default `footer`.
  - `personalization.mail_apply_on`: By default `none`.

Administrators may have to edit configuration file, if they want to re-enable potentially insecure behavior.

**Comment by ikedas** [comment]
We should test if this pr will change behavior reported in #501 .

**Pull request merged**
