### PR TITLE
List admin deletion through command line

### PR DESCRIPTION
**Pull request by dverdin**
This is the follow-up to PR #551.

See issue #524 for discussion about the feature.

I implemented the _deletion_ of a list admin (owner or editor) through the command line.
The code is based on a Request::Handler called delete_list_admin.

You can delete a list admin using the following command:
```
sympa.pl --delete_list_admin \
    --email <email@example.com> \
    --role [owner|editor]
    --list <listname@lists.domain.tld> \
    --robot <lists.domain.tld> \
```
Details about the command:
  - `--email` is mandatory.
  - If you don't specify `--role`, both editor and owner roles will be removed.
  - You also need to specify either `--list` or `--robot`.
    - `--list` is a full list id (<local.part>@<domain.part>) ; if you specify it, the selected role will be deleted for the user in this list only ;
    - `--robot` is the name of a Sympa robot ; if you specify it, the selected role will be deleted for the user in all this robot's lists.

For now, the command refuses to complete for owners only if the user to be deleted if the last list owner. This behaviour should probably be refined.
Here are my thoughts:
  - We could switch the last user with listmaster.
  - We could also add a "force" option that would ignore this protection.
  - It could also be a mitigation of both solutions:
    - for example, force the deletion but replace the email with the sender's email.

To be discussed, I guess.

Todo after it: implement list admin update (for which you could also specify the whole virtual host).

### CODE REVIEW

**Comment by racke** [comment]
If you are fixing bugs in sympa.pl, that should clearly go into a **separate** PR.  And if you concatenate strings please add whitespace for readability.

**Comment by dverdin** [comment]
Oh no, it's a bug in sympa.pl _in the part I just added_.
It is in no way a pre-existing bug.

**Comment by dverdin** [comment]
(Whitespace added) :wink:

**Comment by ikedas** [comment]
> * `--email` is mandatory.
> * If you don't specify `--role`, both editor and owner roles will be removed.
> * You also need to specify either `--list` or `--robot`.

IMO I prefer to make `--role` also mandatory.  As breaking adminship can stop the list, user would be better to know what they are doing.

**Comment by racke** [comment]
> Oh no, it's a bug in sympa.pl _in the part I just added_.
> It is in no way a pre-existing bug.

Good, the commit message was not precise enough to tell me that.

**Comment by dverdin** [comment]
Racke : yes, I'll make commit messages more explicit.

**Comment by dverdin** [comment]
@ikedas : I agree. The reason why I did not make role mandatory was to ease deprovisionning, when you want to remove an address from a whole domain.
However, I added a control to prevent removing the last owner of a list.

**Comment by ikedas** [comment]
Same as #551. Though I haven't investigated, how this will work when `owner_domain` feature is enabled?

**Comment by racke** [comment]
Same problem as #551

**Comment by dverdin** [comment]
Ah, OK, this came out of my sonar.
I'll address this problem.

**Comment by racke** [comment]
Please:

- Always make sure to start from latest commit in sympa-6.2
- Never merge anything, rebase should be fine
- Always check commits you are pushing 
- Always review your PR (commits, files changed)

Enjoy!

**Comment by dverdin** [comment]
No problem.
I'll clean this mess and create new, clear PR.
Thanks for your feedback and a happy new year to you!

**Pull request closed without merging**
