### PR TITLE
Feature: add scenari to restrict message submission to list owners

### PR DESCRIPTION
**Pull request by mpkut**
As part of a long-ago migration from Listproc to Sympa, our site created a send scenario to restrict submission to list owners only. It has proven to be a clear, self-documenting way to implement announcement-only lists that do not require moderation.

This patch adds scenari named "send.owners" and "send.ownerkey" to implement this feature, and updates report.tt2 to say "you must be a list owner to send to this list" when the scenario rejects the submission.

--mic--

### CODE REVIEW

**Comment by ikedas** [comment]
Thanks for useful contribution!

The name `send.owners` would be better to be `send.owner` for consistent naming.

And I feel `send.ownerkey` is a bit exceptional naming.  IMHO `send.ownerauth` seems better.

**Comment by mpkut** [comment]
Thank you for reviewing this submission! I am up for whatever naming seems best. Should I close this pull request and submit another with "send.owners" and "send.ownerauth" as you specify?

**Comment by ikedas** [comment]
@mkput, you need not submit new pull request.  You can do the changes (`git mv send.owners send.owner` and so) on `feature_send_by_owners` branch in your fork, commit them and push.  By doing such, changes will be added to this PR.

**Comment by mpkut** [comment]
OK, thank you - done!

**Pull request merged**
