### PR TITLE
Fix outdated link to Data::Password variables

### PR DESCRIPTION
**Pull request by racke**

### CODE REVIEW

**Comment by ikedas** [comment]
Fixed by modifying catalog on translation server: cf. d073fab

**Comment by racke** [comment]
Sorry, but I don't like this solution. The source code is still outdated and that is reflected in the online documentation.

**Comment by ikedas** [comment]
> Sorry, but I don't like this solution. The source code is still outdated and that is reflected in the online documentation.

The source was modified, too (using [correct_msgid](https://github.com/sympa-community/sympa/blob/sympa-6.2/support/README.support.md#correct_msgid)).

However, since this method needs frequent access to the message catalog, general method (letting translations fuzzy and waiting correction by translators) can be reasonable.

**Comment by ikedas** [comment]
Sorry. I was doing maintenance on the translation server over the weekend, so I applied the suggested updates on my side. Thanks for correcting the message.

**Pull request closed without merging**
