### PR TITLE
Update a dependency MHonArc

### PR DESCRIPTION
**Pull request by ikedas**
See also sympa-community/MHonArc#7

### CODE REVIEW

**Comment by ikedas** [comment]
This fix would be better to be released when the packagers will have been prelared new packages of MHonArc.

**Comment by racke** [comment]
MHonArc is not yet available on CPAN.

**Comment by ldidry** [comment]
And the version currently on PAUSE does not have MHonArc.pm

**Comment by racke** [comment]
> And the version currently on PAUSE does not have MHonArc.pm

@ldidry so how to we go forward, flush the version form PAUSE which seems to be stuck anyway and prepare one with MHonArc.pm?

**Comment by ldidry** [comment]
I think that it’s indeed better to remove the current version from PAUSE (I juste scheduled the deletion) in order to re-add the MHonArc.pm.
I’ll push a branch on github tomorrow to see if its content seems good to you.

**Comment by ikedas** [comment]
> MHonArc is not yet available on CPAN.

See https://metacpan.org/release/LDIDRY/MHonArc-2.6.22
However it has not yet been indexed for cpanm:
http://cpanmetadb.plackperl.org/v1.0/package/MHonArc::UTF8

**Comment by ldidry** [comment]
Should I remove the scheduled deletion of the file?

**Comment by racke** [comment]
> Should I remove the scheduled deletion of the file?

I don't think so. While the direct link above works, it is not indexed within MetaCPAN. What did the email from PAUSE tell you about the indexing?

**Comment by ldidry** [comment]
It failed when uploading the archive. A day or two after that, I got a mail from Neil Bowers.

**Comment by racke** [comment]
That's a tough nut. Can't understand why PAUSE doesn't clean up broken packages by itself. 
At any rate, let's get up a release with MHonArc.pm.

**Comment by ikedas** [comment]
@ldidry , is there any progress?

**Comment by ldidry** [comment]
I just uploaded a new version (2.6.23) to CPAN

**Comment by racke** [comment]
Great, thank you!

**Comment by racke** [comment]
Commandline usage seems to be broken though: https://github.com/sympa-community/MHonArc/issues/12

**Comment by ldidry** [comment]
Wait a bit for the 2.6.24 to be indexed on PAUSE and update the dependency to 2.6.24.

**Pull request merged**
