### PR TITLE
Pictures max size fix

### LINKED ISSUE #180: Hardcoded max picture size in picture_upload.tt2
Subscriber's max picture size defaults to 100 Kb, but can be changed with the pictures_max_size option. However, picture_upload.tt2 hardcodes the 100 Kb value.
https://github.com/sympa-community/sympa/blob/091ebf5b3949e834d30644f815932f76eb23c103/default/web_tt2/picture_upload.tt2#L9

### PR DESCRIPTION
**Pull request by xavierba**
This fixes #180, but I'm not completely satisfied with the fix, as the pictures_max_size will be properly reported but the size will be expressed in bytes, while it would probably be better to report it in kilobytes.

### CODE REVIEW

**Comment by xavierba** [comment]
I've corrected the 2nd commit to use kilobytes again. Thanks for the hint @ikedas :-)

**Comment by racke** [comment]
Change looks good to me 👍

**Comment by ikedas** [comment]
@xavierba, good fixes!

btw, though this question is not related to this fix, what is "JPP" format?

**Comment by xavierba** [comment]
This is most probably a typo for JPG. See https://github.com/sympa-community/sympa/blob/407a17e4a8cea342c3657fe8243a6855a9621685/src/cgi/wwsympa.fcgi.in#L13919
I've added one more commit to fix it.

**Pull request merged**
