### PR TITLE
Invalid default scenarios

### PR DESCRIPTION
**Pull request by ikedas**
Fixed bugs:

  - WWSympa: On list config page, default settings of list scenarios are ignored. And if user updated configuration, the first option in select box is saved.
    Fixed by assigning defaults in Sympa::ListDef.
  - `archive.web_access` list parameter did not have default value.

Change:
  - The feature making a symbolic link "*.default" to assign default values of scenarios is deprecated.
    It was hard to determine original option value linked to default.

### CODE REVIEW

**Comment by dverdin** [comment]
cool!
I was about to argue about *.default but you're right: we don't care about it. It was never actually used.
So, yes, godspeed!

**Comment by dverdin** [comment]
Hey, I'm stupid.
I can't believe I did not see it: how do you define the default scenario now?
Except by modifying ListDef, of course; I mean: how do you define the default scenario when you're an administrator? Most of these parameters don't have a sympa.conf default value.
An people having defined custom default scenarios will have their defaults ignored when upgrading.
Soji, we fucked up. This PR is a disaster. Please roll back and let's think  about it again.

**Comment by ikedas** [comment]
Except by modifying ListDef? None. As I summed up, the feature defining defaults by symblic link haven't worked correctly. In other words, there have never been such ways.

**Comment by dverdin** [comment]
Wait... So this feature NEVER worked?

**Comment by dverdin** [comment]
Then, how does Sympa determines the default scenario for now?

**Comment by ikedas** [comment]
@dverdin, are you feeling calm now?

I added robot-/site- level defaults to list scenario parameters, as the other list parameters have.  See #540.
If you found something wrong, please let us know.

I'll merge it in these weekdays.

**Comment by dverdin** [comment]
@ikedas : Yes I do. Sorry for losing my calm. I should know better and trust your judgement since the time...
Setting the defaults in the server / virtual host configuration is perfect to me. 
So you got rid of a confusing bug and even improved Sympa.
As far as I'm concerned, it's OK to close these issues.
And in the future, I'll take deep breathes before commenting.
Regards,
David

**Pull request merged**
