### PR TITLE
 Use tidyall to ease tidying files

### PR DESCRIPTION
**Pull request by ldidry**
Follow-up of #438 

- Code::TidyAll added as develop requirement in cpanfile
- Add tidyall target to Makefile.am (to run it with the good options
  without pain)
- Add dot/dot.tidyallrc
- Add t/ and xt/ to perltidy test

\+ Tidy up src/ t/ xt/ files

### CODE REVIEW

**Comment by ikedas** [comment]
Is there any reason why Test::PerlTidy can’t test *.fcgi.in ?

**Comment by ldidry** [comment]
Hardcoded values, that's all: https://metacpan.org/source/LARRYL/Test-PerlTidy-20130104/lib/Test/PerlTidy.pm#L130

**Comment by ikedas** [comment]
What a self-righteousness!

However, we could add self-made run_tests(), couldn’t we?  I can try it.

**Comment by ikedas** [comment]
@ldidry, if you are ok for the PR above, please merge it and fix this PR.  Then I'll merge this PR.

**Comment by ldidry** [comment]
I'll do that tomorrow. Thanks :+1:

**Comment by ldidry** [comment]
I tested your PR, it's working fine :ok_hand: 

I'm not sure of the workflow that you want:f do you want me to merge your PR in my branch or do you want me to merge your PR in sympa-6.2?

**Comment by ikedas** [comment]
I think of both pr to be merged into sympa-6.2 branch: When you merged my pr to sympa-6.2, I think you will have to fix your pr to resolve conflict before I will merge it to sympa-6.2.

**Comment by ikedas** [comment]
@ldidry, thanks for merging my PR. There are big conflicts due to the other commit. I'll solve them and complete merger.

**Comment by ikedas** [comment]
Done :tada:.

**Pull request merged**
