### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by fingolfin**
This fixes a bunch of typos.

You might not want to merge this as-is, as it could break existing
installation with customized templates? But I don't know what your
policies on this are esp. how you prefer to deal with it; so I just
did a global "search and replace", and hope you can give a hint as
to which places (if any) I maybe should not touch.

Or perhaps you don't mind and want to just merge :-).

### CODE REVIEW

**Comment by ikedas** [comment]
@fingolfin , thank you for the corrections!

Among your fixes, these would be better to be corrected by submitting PR.

  - Changes of a parameter name in the code:
      - default/web_tt2/review.tt2
      - src/cgi/wwsympa.fcgi.in

    (A suggestion on the fix: For templates customized for earlier versions, it is better to duplicate parameter value for old parameter name as well.)

  - Correction in the source commnent:
      - support/xgettext.pl

The others, typos in the messages/strings to be translated, may be corrected by adding correction on the translation server. --- If possible, please add your fix to english catalog:

  - On [English page of translation site](https://translate.sympa.org/en_US/), add correct string as a "translation" of incorrect msgid.

Your changes on the site above will be reflected to source distribution in the future release.  PO files need not be corrected manually, as they will also be updated accordingly.

**Comment by racke** [comment]
IMHO typos in the source code should be fixed there and not only in the English translation. Otherwise the typos are exposed and diligent contributors will report them again. The approach in #1426 is the way it should be done.

**Comment by ikedas** [comment]
> IMHO typos in the source code should be fixed there and not only in the English translation. Otherwise the typos are exposed and diligent contributors will report them again. The approach in #1426 is the way it should be done.

My approach to #1426 was [to modify _both_ the source code and the message catalog _at once_](https://github.com/sympa-community/sympa/commit/d073fab) based on the single information entered into the translation server (we can do this with the [correct_msgid](https://github.com/sympa-community/sympa/blob/sympa-6.2/support/correct_msgid) script: Please confirm the content of script).  I don't think the pain of another report coming in before above process is complete is much different than the pain of a PR being submitted with the same fixes before one PR has been merged.

Anyways, if you have objection to the method that was used to solve #115, How about discussing it not as an issue about this PR but as a more general release management issue?  In the case of this PR, please let us do it the way we have been doing it.

**Comment by ikedas** [comment]
@fingolfin , sorry for the confusion.  As I'll fix "the others" in [previous comment](https://github.com/sympa-community/sympa/pull/1432#issuecomment-1166073959), could you please submit another PR to fix remainder, parameter names and comment in sources code?  Thank you.

**Comment by fingolfin** [comment]
@ikedas I made PR #1433 but it wasn't clear to me what you want to be in there and what not... so for now I just dropped the changes to `po` files there. Please let me know if I should drop more (and what)

**Comment by ikedas** [comment]
Hi @fingolfin ,

At least po files are prone to conflicts, so you don't have to correct them in the PR.
Further complication would be a burden on you, so I will accept your PR and make other adjustments on my side.

Thank you for your careful corrections!

**Pull request closed without merging**
