### PR TITLE
Cannot include privileged owner from list even if it has to (#969)

### LINKED ISSUE #969: Cannot include privileged owner from list even if it has to
Trying to include a serie of privileged owner from other list. The included owners are not privileged even if I choose in the drop down menu to do so. Raising included owner to privileged is possible by hand afterwards, one by one.

Version
-------
6.2.54

Installation method
-------------------
Updated from source installed SYMPA 6.1.25 to , still from source, SYMPA 6.2.54.

Expected behavior
-----------------
Include owners from other list. Choose privileged owner in dropdown menu. Should included owners tagged with a star as privileged have.
owner_include, source_parameters <list>, profile "privileged"

Actual behavior
---------------
Included owners from list does not have a star. The elevation of right to privileged is possible by hand by listmaster.

Additional information
----------------------

err main::#1541 > main::do_edit_list#10622 >
Sympa::List::sync_include_admin#4854 > Sympa::Spindle::spin#95 >
Sympa::Request::Handler::include::_twist#188 >
Sympa::Request::Handler::include::_update_inclusion_table#552 >
Sympa::Database::do_prepared_query#382 Unable to execute SQL statement
"INSERT INTO inclusion_table (target_inclusion, role_inclusion,
source_inclusion, update_epoch_inclusion) VALUES (?, ?, ?, ?)": (23000)
Duplicate entry 'listea@unifr.ch-listeb@unifr.ch-owner' for key 'PRIMARY'
Jul  3 14:45:59 svx-sympa2 wwsympa[34828]: err main::#1541 >
main::do_edit_list#10622 > Sympa::List::sync_include_admin#4854 >
Sympa::Spindle::spin#95 > Sympa::Request::Handler::include::_twist#188 >
Sympa::Request::Handler::include::_update_inclusion_table#573 Unable to
update list Sympa::List <listeb@unifr.ch> in database

### PR DESCRIPTION
**Pull request by ikedas**
This may fix #969 .

### CODE REVIEW

**Comment by bmarchal54** [comment]
Hello
I just tried to upgrade to version 6.2.56. In this version, I had the same problem with not carrying 'privileged' for owners included through a list.
I have the following concern:
Erreurs : Not an ARRAY reference at /usr/share/sympa/lib/Sympa/List.pm line 4752.
Pile d'appel

DIED: Not an ARRAY reference at /usr/share/sympa/lib/Sympa/List.pm line 4752.
 at /usr/share/sympa/lib/Sympa/List.pm line 4752.
	Sympa::List::_load_include_admin_user_file(Sympa::List <dn-test-benoit@tmp.univ-lorraine.fr>, HASH(0x776cf68)) called at /usr/share/sympa/lib/Sympa/Request/Handler/include.pm line 99
	Sympa::Request::Handler::include::_get_data_sources(Sympa::List <dn-test-benoit@tmp.univ-lorraine.fr>, 'owner') called at /usr/share/sympa/lib/Sympa/Request/Handler/include.pm line 136
	Sympa::Request::Handler::include::_twist(Sympa::Spindle::ProcessRequest=HASH(0x75d0e08), Sympa::Request <action=include;context=dn-test-benoit@tmp.univ-lorraine.fr;role=owner>) called at /usr/share/sympa/lib/Sympa/Spindle.pm line 95
	Sympa::Spindle::spin(Sympa::Spindle::ProcessRequest=HASH(0x75d0e08)) called at /usr/share/sympa/lib/Sympa/List.pm line 4789
	Sympa::List::sync_include(Sympa::List <dn-test-benoit@tmp.univ-lorraine.fr>, 'owner') called at /usr/share/sympa/lib/Sympa/List.pm line 407
	Sympa::List::new('Sympa::List', 'dn-test-benoit', 'tmp.univ-lorraine.fr', HASH(0x7761af0)) called at /usr/libexec/sympa/wwsympa.fcgi line 10637
	main::do_edit_list() called at /usr/libexec/sympa/wwsympa.fcgi line 1556

If you could tell me where my mistake is.

cordially

**Comment by racke** [comment]
Sympa 6.2.56 was released on 24th May, thus it doesn't include this fix.

**Comment by bmarchal54** [comment]
Yes, I reported this one in the code of the List.pm module.
And that caused the error I gave.

**Comment by ikedas** [comment]
@bmarchal54 , could you please show the configuration related to `owner_include` ?

**Comment by bmarchal54** [comment]
Hello, 

Here is the owner_include paragraph of the config file. 
The error occurs regardless of the privileged type or not. 

--------------------------- 
owner_include 
source inclusion-liste 
reception mail 
profile normal 
visibility noconceal 
source_parameters dn-test-proprietaires@tmp.univ-lorraine.fr 
-------------------------- 

Without the patch, there is indeed the insertion of the people from the list in the admin_table table, but in 'normal' mode. 

cordially 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 / 06.07.35.50.65 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
So what is the content of `inclusion-liste.incl`?

**Comment by bmarchal54** [comment]
Here is the contents of the file 

----------------- 
more /etc/sympa/data_sources/inclusion-liste.incl 
include_list [% param.0 %] 
---------------- 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 / 06.07.35.50.65 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by bmarchal54** [comment]
Hello, 

I tried to see what was wrong with the patch by showing the type of structure pointed to by the $cfgs variable. 
Sometines, these are ARRAYs, but there are also HASHs. Wouldn't it come from there? 

See you soon 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 / 06.07.35.50.65 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
> Sometines, these are ARRAYs, but there are also HASHs. Wouldn't it come from there?

Can you dump the content of `$cfgs` ?

**Comment by bmarchal54** [comment]
Hello, 

Here is the code I inserted to display the contents of the variable: 

------------------- 
foreach my $cfgs (values %include) { 
$log->syslog('notice', 
'patch : valeurs type : %s', 
$cfgs); 
$log->syslog('notice', 
'patch : valeurs type : %s', 
Dumper($cfgs)); 
print FICDUMPER Dumper($cfgs); 
} 
------------------- 

And here is the result in the logs of Sympa : 
------------------- 
Sep 4 14:15:32 vacherin wwsympa[107155]: notice Sympa::List::_load_include_admin_user_file() patch : valeurs type : ARRAY 
Sep 4 14:15:32 vacherin wwsympa[107155]: notice Sympa::List::_load_include_admin_user_file() patch : valeurs type : $VAR1 = [#012 {#012 'filter' => undef,#012 'listname' => 'dn-test-proprietaires@tmp.univ-lorraine.fr',#012 'name' => 'include_list dn-test-proprietaires@tmp.univ-lorraine.fr'#012 }#012 ]; 
Sep 4 14:15:32 vacherin wwsympa[107155]: notice Sympa::List::_load_include_admin_user_file() patch : valeurs type : HASH 
Sep 4 14:15:32 vacherin wwsympa[107155]: notice Sympa::List::_load_include_admin_user_file() patch : valeurs type : $VAR1 = {}; 

------------------- 
Hope this can help you. 

Kind regards 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 / 06.07.35.50.65 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by bmarchal54** [comment]
If I add the following line in the code, I no longer have an error:

     foreach my $ cfgs (values% include) {
+       **next if ref $ cfgs ne 'ARRAY';**
         foreach my $ cfg (@ {$ cfgs || []}) {

But it may not be complete. In any case, with a quick test, the members of the list pass well as privileged owner.

**Comment by ikedas** [comment]
@bmarchal54 , if possible, can you dump whole value of ``%include``?
``` perl
$log->syslog('notice', 'patch : valeurs : %s', Dumper(\%include));  # <- Insert this
foreach my $cfgs (values %include) {
...
```

**Comment by bmarchal54** [comment]
Hello 
Here is the result in the log file 

------ 
Sep 9 08:18:02 vacherin wwsympa[3142]: notice Sympa::List::_load_include_admin_user_file() patch : valeurs : $VAR1 = {#012 'include_sympa_list' => [#012 {#012 'filter' => undef,#012 'listname' => 'dn-test-proprietaires@tmp.univ-lorraine.fr',#012 'name' => 'include_list dn-test-proprietaires@tmp.univ-lorraine.fr'#012 }#012 ],#012 'defaults' => {}#012 }; 
----- 

Cordially 
--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 / 06.07.35.50.65 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
@bmarchal54 ,please apply [this additional patch](https://github.com/sympa-community/sympa/commit/d3a2dfe.patch) and check if the problem will be solved.

**Comment by bmarchal54** [comment]
If I delete the line "next if ref $cfgs ne 'ARRAY';", I have this message again 

Pile d'appel 
DIED: Not an ARRAY reference at /usr/share/sympa/lib/Sympa/List.pm line 4778.
 at /usr/share/sympa/lib/Sympa/List.pm line 4778.
	Sympa::List::_load_include_admin_user_file(Sympa::List <dn-test-benoit@tmp.univ-lorraine.fr>, HASH(0x73fd210)) called at /usr/share/sympa/lib/Sympa/Request/Handler/include.pm line 99
	Sympa::Request::Handler::include::_get_data_sources(Sympa::List <dn-test-benoit@tmp.univ-lorraine.fr>, 'owner') called at /usr/share/sympa/lib/Sympa/Request/Handler/include.pm line 136
	Sympa::Request::Handler::include::_twist(Sympa::Spindle::ProcessRequest=HASH(0x7111218), Sympa::Request <action=include;context=dn-test-benoit@tmp.univ-lorraine.fr;role=owner>) called at /usr/share/sympa/lib/Sympa/Spindle.pm line 95
	Sympa::Spindle::spin(Sympa::Spindle::ProcessRequest=HASH(0x7111218)) called at /usr/share/sympa/lib/Sympa/List.pm line 4815
	Sympa::List::sync_include(Sympa::List <dn-test-benoit@tmp.univ-lorraine.fr>, 'owner') called at /usr/share/sympa/lib/Sympa/List.pm line 411
	Sympa::List::new('Sympa::List', 'dn-test-benoit', 'tmp.univ-lorraine.fr', HASH(0x73c8160)) called at /usr/libexec/sympa/wwsympa.fcgi line 10637
	main::do_edit_list() called at /usr/libexec/sympa/wwsympa.fcgi line 1556 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 / 06.07.35.50.65 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
Please restart wwsympa service (cf. [Reloading WWSympa](https://sympa-community.github.io/manual/admin/services.html#reloading-wwsympa)).

**Comment by bmarchal54** [comment]
I did 
Shouldn't I change my long-standing inclusion.incl file? 
Put include_sympa_list instead of include_list 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 / 06.07.35.50.65 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
@bmarchal54 , please show the dump of `%include`.

**Comment by bmarchal54** [comment]
Here is the result 

notice Sympa::List::_load_include_admin_user_file() patch : valeurs : $VAR1 = {#012 'include_sympa_list' => [#012 {#012 'filter' => undef,#012 'listname' => 'dn-test-proprietaires@tmp.univ-lorraine.fr',#012 'name' => 'include_list dn-test-proprietaires@tmp.univ-lorraine.fr'#012 }#012 ],#012 'defaults' => {}#012 }; 

Thanks 
--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 / 06.07.35.50.65 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
And please show the content of `*.incl` file(s) and all `owner_include` paragraph(s) in `config` file.

**Comment by bmarchal54** [comment]
Here are the files. There is only one * .incl 

inclusion-liste.incl 
------- 
include_list [% param.0 %] 
------ 

config file : 
------- 
..... 
owner_include 
source inclusion-liste 
reception mail 
profile privileged 
visibility noconceal 
source_parameters dn-test-proprietaires@tmp.univ-lorraine.fr 
..... 

----- 
--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 / 06.07.35.50.65 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
@bmarchal54 , please apply [this additional patch](https://github.com/sympa-community/sympa/commit/19b8dc1.diff) for the time being.  It will be included in the next release.
Thanks!

**Comment by bmarchal54** [comment]
Hello,
I am on leave for two weeks without access to a computer (except e-mail).
I could not do the modifications and the tests before.
I will keep you posted as soon as possible.
cordially

---
Benoît Marchal
Sous-direction des infrastructures
Direction du Numérique
Université de Lorraine
Benoit.Marchal@univ-lorraine.fr

**Pull request merged**
