### PR TITLE
Cosmetic problems in Listmaster Admin menu

### PR DESCRIPTION
**Pull request by qosobrin**
This PR was created to correct the cosmetic problems detailed in issue #1294

### CODE REVIEW

**Comment by racke** [comment]
Thanks for your contribution, but I think the pull request should use only a single commit. Also it is a better approach to create a dedicated branch for pull requests in your repository.

**Comment by qosobrin** [comment]
Sorry for that, @racke. Do you prefer me to repeat the PR with a single commit? It's not problem at all.

**Comment by racke** [comment]
Yes please do that.

**Comment by qosobrin** [comment]
I'm closing this PR to create a cleaner one as requested by @racke

**Pull request closed without merging**
