### PR TITLE
Unify scenario names

### PR DESCRIPTION
**Pull request by qosobrin**
I renamed the files myself. This changes are related to https://github.com/sympa-community/sympa/issues/216

### CODE REVIEW

**Comment by qosobrin** [comment]
I missed to include the source files that pointed to the renamed scenario files. I will try to include them later.

**Comment by ikedas** [comment]
Hi @qosobrin,

If it is difficult to add the other commits to this PR, please feel free to close this PR and retry to submit new one.

**Comment by racke** [comment]
Also there is an Archive.zip file that doesn't belong here.

**Comment by ikedas** [comment]
I'm willing to merge content of archive but, if qosobrin may, additional commits would be better.

**Comment by ikedas** [comment]
See update: PR #227

**Pull request closed without merging**
