### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by bikepunk**
fix a wrong translation

### CODE REVIEW

**Comment by bikepunk** [comment]
the first commit has trouble with line endings, because of using the github web editor :
"We’ve detected the file has mixed line endings. When you commit changes we will normalize them to Windows-style (CRLF)."

I don't know the workaround with CLI :-|

**Comment by ikedas** [comment]
Thanks for fixes!

**Comment by bikepunk** [comment]
just hoping the Windows-style (CRLF) line endings won't break anything.

**Comment by ikedas** [comment]
> just hoping the Windows-style (CRLF) line endings won't break anything.

I couldn't find any evidence that gettext allows CRLF as line endings, but it's likely.  Do you know of any sources that explicitly state  that?

**Comment by bikepunk** [comment]
> > just hoping the Windows-style (CRLF) line endings won't break anything.
> 
> I couldn't find any evidence that gettext allows CRLF as line endings, but it's likely. Do you know of any sources that explicitly state that?

no sources (I'm not dev BTW). just (most probably) unnecessary worries.

**Pull request merged**
