### PR TITLE
Bulk test

### PR DESCRIPTION
**Pull request by eiro**
this is a very beginning of the bulk test

### CODE REVIEW

**Comment by ikedas** [comment]
Hi @eiro,
There are no enough number of test cases. Would you please submit again when you fill have filled them?

**Comment by eiro** [comment]
hello @ikedas,

On Thu, Sep 27, 2018 at 02:35:49PM -0700, IKEDA Soji wrote:
> Hi @eiro,
> There are no enough number of test cases.

agreed: it was a very first step but i don't want to work on something
that could be rejected.

> Would you please submit again when you fill have filled them?

i will of course. can you please review this PR and tell me if something
is wrong for you?

regards
marc

**Comment by ikedas** [comment]
Hi @eiro,

> > Would you please submit again when you fill have filled them?
> 
> i will of course. can you please review this PR and tell me if something
> is wrong for you?

I’m sorry but, honestly, it’s hard to review this PR.

  - This looks intended to unit tests, while there are no meaningful test cases described.
  - In spite it is for the test, a change on target code is made.
  - Including the points above, there is no intelligible summary in initial comment to describe what the submitter aims to realize with this PR.

Could you please learn from PRs by other people and please submit PR to be right? You may take enough time: We can wait as long as you need.

**Comment by eiro** [comment]
agreed

**Pull request closed without merging**
