### PR TITLE
Add unsubscribe command to remove emails from list in sympa.pl

### PR DESCRIPTION
**Pull request by kukoarmas**
In the sympa.pl CLI we have the "import" option to add subscribers to a list, but we lack a similar command to remove subscribers from the list.
This command is useful if you need to remove subscribers from a batch script

### CODE REVIEW

**Comment by ikedas** [comment]
For me, this PR seems related to #901/#902. IMHO `--add` and `--del` (or maybe `--add_member` and `--del_member`) would be better to be implemented.

**Comment by kukoarmas** [comment]
> For me, this PR seems related to #901/#902. IMHO `--add` and `--del` (or maybe `--add_member` and `--del_member`) would be better to be implemented.

Do you mean that I should implement those two commands? If I implement --add_member for multiple entries, wouldn't it duplicate the --import functionality?

I'm ok implementing both commands, I'm just asking ;)

**Comment by ikedas** [comment]
> Do you mean that I should implement those two commands? If I implement --add_member for multiple entries, wouldn't it duplicate the --import functionality?

No you may not, if you will wait for the work by @dverdin progressing.

N.B. I think the “--import“ option On CLI was introduced for consistency with “Multiple add” function on web GUI.  The “del” function looks not having multiple counterpart.

**Comment by ikedas** [comment]
@kukoarmas , sorry for delayed merge.  As @dverdin 's work got stuck, this PR was merged first.

The name of command was changed to "del" standing for the action by admins to delete any subscribers.

Thank you for your contribution!

**Pull request merged**
