### PR TITLE
Empty paragraph in list config should not be warned.

### PR DESCRIPTION
**Pull request by ikedas**
See also https://listes.renater.fr/sympa/arc/sympa-fr/2020-11/msg00040.html for details.

### CODE REVIEW

**Comment by ikedas** [comment]
Hi @bmarchal54 , could you check this ?

**Comment by bmarchal54** [comment]
Hello,
I'm sorry, but I'm not very expecting in app development.
What do I have to test?
Kind regards

**Comment by ikedas** [comment]
> I'm sorry, but I'm not very expecting in app development.
> What do I have to test?

If you are still experiencing the problem about logging, if possible, could you please apply the change by this PR and see if the problem will be solved?

Note that I don't recommend to apply the change on production server.

**Comment by bmarchal54** [comment]
I don't know what change you are asking me to apply.
Frankly, git is a mystery to me.
I am on 6.2.60 on my test server.

**Comment by ikedas** [comment]
> I don't know what change you are asking me to apply.

Sorry for poor instruction. Could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/1150.patch), (restart Sympa services as necessity) and check if the problem will be solved?

**Comment by bmarchal54** [comment]
It's a bit like me who is not very efficient. Do not apologize.
I no longer have the error / warning message in the logs.

The problem which is at the origin of this is still the rewriting of the configuration file of the list which forgets (or forgot in previous versions of SYMPA) to carry over the lines of the paragraph.

cordially

**Comment by ikedas** [comment]
> I no longer have the error / warning message in the logs.

Thank you for confirming!  This fix will be included in the next of the next release (maybe 6.2.64).

> The problem which is at the origin of this is still the rewriting of the configuration file of the list which forgets (or forgot in previous versions of SYMPA) to carry over the lines of the paragraph.

I think so too.  I guess config file has been modified during upgrading process, however I haven't find out where it has been done.

**Comment by bmarchal54** [comment]
Hello, 

I have not had the message in the logs since the passage of your patch. 
Indeed, it had been a while since there was this one, in me a version 6.1, I think and maybe even before. 

Have a good day 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 / 06.07.35.50.65 
mél : ***@***.***

**Pull request merged**
