### PR TITLE
Remove undocumented backtick syntax in sympa.conf

### LINKED ISSUE #1086: Remove undocumented backtick syntax in sympa.conf
Backtick syntax (`` `...` ``) in `sympa.conf` should be removed, because it allows to execute arbitrary code.

Note: that syntax has not been documented yet.

### PR DESCRIPTION
**Pull request by ikedas**
This may fix #1086

### CODE REVIEW

**Comment by racke** [comment]
It is very good to remove this "backdoor". But why keep it as comment?

**Comment by ikedas** [comment]
No particular reason. Conf.pm will be removed by radical refactoring anyway, so I thought I'd remind ourselves what _not_ to do in the new code.

**Comment by racke** [comment]
Well, if you ask me we should remove it right away. I'm sure we don't produce code like that anymore.

**Comment by ikedas** [comment]
Ok, I'll do it.

**Comment by dverdin** [comment]
Indeed, it was definitely a trace from the past. If somebody enabled the conf edition on the web interface, it was a way to get/modify data from the whole server; Particularly concerning in the case of virtual domains hosting.
Would it be a good idea to issue a security notice when releasing this change?

**Comment by racke** [comment]
It is still used in the Debian packages, but I will take care of that. 

@ikedas Are there any other known security problems left?

**Comment by dverdin** [comment]
Would it be wrong to make a new tag only for this issue?

**Comment by ikedas** [comment]
> It is still used in the Debian packages, but I will take care of that.
> 
> @ikedas Are there any other known security problems left?

At least problems related to parsing configuration file, I don't know the other problems.

**Comment by ikedas** [comment]
Updated.  Now the process of Sympa terminates if backtick is contained in sympa.conf so that administrators have to update configuration manually.

**Comment by ikedas** [comment]
If no objection, I'll merge this.

**Pull request merged**
