### PR TITLE
Obfuscate cookie

### PR DESCRIPTION
**Pull request by xavierba**
Tentative fix for #243, currently untested.

### CODE REVIEW

**Comment by racke** [comment]
Eval doesn't make sense to me for calling chmod function. I doubt it will crash in normal situations and also you need to check if the chmod was successful anyway.

**Comment by xavierba** [comment]
I just copy/paste'd the code above which does the chown. What would you suggest instead ?

**Comment by racke** [comment]
Copy/paste from where?

**Comment by xavierba** [comment]
From _save_binary_cache in src/lib/Conf.pm, just above the lines I've added.

**Comment by ikedas** [comment]
As discussed on irc meeting, this PR is closed. #250 will survive.

**Pull request closed without merging**
