### PR TITLE
Replace obsolete Ansible role in README

### PR DESCRIPTION
**Pull request by racke**

### CODE REVIEW

**Comment by ikedas** [comment]
How about swapping current repository with yours? In other words, how about moving `ansible-role-sympa` to sympa-community?

**Comment by racke** [comment]
Yes, I can certainly move ansible-role-sympa to sympa-community. I would like to retain the name ansible-role-sympa though.

**Comment by ikedas** [comment]
I think the name ansible-role-sympa is fine.

**Comment by racke** [comment]
Moved the repository to sympa-community. My next step would be to add a notice to the obsolete repository and archive that. Is that OK @ikedas

**Comment by ikedas** [comment]
Okey!

**Review by ikedas — APPROVED** [review]

**Pull request merged**
