### PR TITLE
Removed extra periods at the end of these sentences

### PR DESCRIPTION
**Pull request by qosobrin**
There was a period both in the localization string and outside it in these sentences. This error caused doble periods to be displayed in the rendered pages.

### CODE REVIEW

**Comment by qosobrin** [comment]
I add some more changes to the ticket.tt2 file. Some variables were being requested but not used.

**Comment by qosobrin** [comment]
Spaces were missing between checkboxes and labels, making the output somewhat tighten

**Comment by qosobrin** [comment]
Added a new correction to improve readability of "Edit list templates" page.

**Comment by qosobrin** [comment]
When displaying the properties of documents and folders the name of the element was missing in the "Description of %1" string. In the d_properties.tt2 file the loc tag was requesting a variable that does not exist (fname). I changed to the correct one (shared_doc.name) and now it works as expected.

**Comment by qosobrin** [comment]
@ikedas, I have finished my translation of sympa into Galician, that was the reason I have been proofing sympa interface. I am not going to add more issues to this pull request. You can merge it with sympa source when you wish.

**Comment by ikedas** [comment]
@qosobrin, thanks for proofreading.  I merged your corrections.

**Comment by qosobrin** [comment]
Your are welcome, @ikedas. It's me who should be thanking you for all the effort you put in the project.

I understand that it is safe for me to remove my local branch, no? I still feel a little bit unsafe in the git world.

Regards,

**Pull request merged**
