### PR TITLE
Add autofocus to input text web

### PR DESCRIPTION
**Pull request by dominiquefournier**

### CODE REVIEW

**Comment by ikedas** [comment]
Hi @dominiquefournier ,

Could you please combine multiple PRs into one?

---
BTW, IMHO we'd be better to [consider accessibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus#accessibility_considerations). Is there a good way to deal with this?

**Comment by dominiquefournier** [comment]
@ikedas I don't know how combine multiple PR into one. Do you have a documentation ?

**Comment by ikedas** [comment]
You'd be better to re-submit a new PR including multiple commits.

**Comment by ikedas** [comment]
Additionally, how about adding autofocus attribute to these as well?
-   login.tt2
-   renewpasswd.tt2

**Pull request closed without merging**
