### PR TITLE
🎨 — Code tidying

### PR DESCRIPTION
**Pull request by ldidry**

### CODE REVIEW

**Review by ikedas — COMMENTED** [review]
I include a step to run `make tidyall` in the process to release the new version... Ah, sometimes I might forgot to do... Anyway, I think code tidying may not be submitted as PR.

**Comment by ldidry** [comment]
Do you mean that I should directly push to sympa-6.2?

**Comment by ikedas** [comment]
> Do you mean that I should directly push to sympa-6.2?

No. I mean that you never need submitting nor comitting code tidying by yourself.   See [commit log just before release of 6.2.54](https://github.com/sympa-community/sympa/commits/6.2.54) for example.  Thanks to tidyall rule you added, I can perform it as a part of routine work to release new version.

**Comment by ldidry** [comment]
Oh, ok. Closing it :slightly_smiling_face:

**Pull request closed without merging**
